services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # ðŸ”‘ THIS IS CRITICAL
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "/create-topics.sh"]
    volumes:
      - ./kafka/create-topics.sh:/create-topics.sh

  producer:
    build: ./services/producer-service
    depends_on:
      - kafka
    ports:
    - "8000:8000"  # FastAPI
    - "8001:8001"  # Prometheus metrics
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  consumer:
    build: ./services/consumer-service
    depends_on:
      - kafka
    ports:
    - "8002:8002"  # Prometheus metrics
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  alert-service:
    build: ./services/alert-service
    depends_on:
      - kafka
    ports:
      - "8101:8000"
    env_file:
      - .env
