name: Alert Service â€“ Build & Deploy

on:
  push:
    paths:
      - .github/workflows/alert-service.yml

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: g5-health-monitor-alert-service
  ECS_CLUSTER: g5-iot-health-monitor
  ECS_SERVICE: alert-service  
  CONTAINER_NAME: alert-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::255945442255:role/github-actions-ecr-ecs
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, push image
      id: build-image
      working-directory: services/alert-service
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
         

        echo "ECR_REGISTRY=$ECR_REGISTRY"
        echo "Building image with tag: $IMAGE_TAG"

        docker build \
          -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} \
          .

        docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: g5_ecs_task_execution/alert-service.json
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        image: |
          ${{ env.CONTAINER_NAME }}=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.build-image.outputs.image }}
    
    - name: Debug task definition path
      run: |
        pwd
        ls -R