name: Alert Service â€“ Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - feature 
    paths:
      - services/alert-service/**
      - terraform/**
      - .github/workflows/alert-service.yml         
  pull_request:
    branches:
      - main        # Trigger on PRs targeting main
    paths:
      - services/alert-service/**
      - terraform/**
      - .github/workflows/alert-service.yml

env:
  AWS_REGION: us-east-1
  UAT_ECR_REPO: uat-health-monitor-alert-service
  PROD_ECR_REPO: prod-health-monitor-alert-service

  UAT_CLUSTER: uat-iot-health-monitor
  PROD_CLUSTER: prod-iot-health-monitor
  ECS_SERVICE: iot-alert
  CONTAINER_NAME: alert

jobs:
  uat_deploy:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to UAT ECR
        id: login-uat-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image for UAT
        working-directory: services/alert-service
        run: |
          IMAGE_TAG=uat-${{ github.sha }}
          ECR_REGISTRY=${{ steps.login-uat-ecr.outputs.registry }}
          docker build \
          -t $ECR_REGISTRY/$UAT_ECR_REPO:$IMAGE_TAG \
          .
      
      - name: Render ECS Task Definition for UAT
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ env.UAT_IMAGE }}

      - name: Deploy ECS Service for UAT
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: ${{ env.UAT_CLUSTER }}
          service: ${{ env.ECS_SERVICE }}
          task-definition: ecs-task-def.json
          force-new-deployment: true

  prod_deploy:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Prod ECR
        id: login-prod-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get latest UAT image tag
        run: |
          UAT_IMAGE_TAG=$(aws ecr describe-images \
            --repository-name $UAT_ECR_REPO \
            --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[?starts_with(@, `uat-`)]' \
            --output text)
          echo "UAT_IMAGE_TAG=$UAT_IMAGE_TAG" >> $GITHUB_ENV

      - name: Pull and push UAT image to PROD
        run: |
          ECR_REGISTRY=${{ steps.login-prod-ecr.outputs.registry }}
          docker pull $ECR_REGISTRY/$UAT_ECR_REPO:$UAT_IMAGE_TAG
          docker tag $ECR_REGISTRY/$UAT_ECR_REPO:$UAT_IMAGE_TAG $ECR_REGISTRY/$PROD_ECR_REPO:$UAT_IMAGE_TAG
          docker push $ECR_REGISTRY/$PROD_ECR_REPO:$UAT_IMAGE_TAG
          echo "PROD_IMAGE=$ECR_REGISTRY/$PROD_ECR_REPO:$UAT_IMAGE_TAG" >> $GITHUB_ENV

      - name: Render ECS Task Definition for PROD
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ env.PROD_IMAGE }}

      - name: Deploy ECS Service for PROD
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: ${{ env.PROD_CLUSTER }}
          service: ${{ env.ECS_SERVICE }}
          task-definition: ecs-task-def.json
          force-new-deployment: true