name: Alert Service â€“ Build & Deploy

on:
  push:
    paths:
      - alert-service/**
      - .github/workflows/alert-service.yml

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: g5-health-monitor-alert-service
  ECS_CLUSTER: g5-iot-health-mointor
  ECS_SERVICE: alert-service  
  CONTAINER_NAME: alert-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::255945442255:role/github-actions-ecr-ecs
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, push image
      id: build-image
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        docker build -t $ECR_REPOSITORY ./alert-service
        docker tag $ECR_REPOSITORY:latest \
        ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: g5_ecs_task_execution/alert-service.json
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        image: |
          ${{ env.CONTAINER_NAME }}=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.build-image.outputs.image }}
