name: Alert Service â€“ Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - feature        # Trigger on all branches except main
  pull_request:
    branches:
      - main        # Trigger on PRs targeting main

env:
  AWS_REGION: us-east-1
  UAT_ECR_REPO: uat-health-monitor-alert-service
  PROD_ECR_REPO: prod-health-monitor-alert-service

jobs:
  uat_deploy:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to UAT ECR
        id: login-uat-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image for UAT
        run: |
          IMAGE_TAG=uat-${{ github.sha }}
          ECR_REGISTRY=${{ steps.login-uat-ecr.outputs.registry }}
          docker build \
          -t $ECR_REGISTRY/$UAT_ECR_REPO:$IMAGE_TAG \
          -t $ECR_REGISTRY/$UAT_ECR_REPO:latest 
      
      - name: Push Docker image to UAT
        run: |
          IMAGE_TAG=uat-${{ github.sha }}
          ECR_REGISTRY=${{ steps.login-uat-ecr.outputs.registry }}
          docker push $ECR_REGISTRY/$UAT_ECR_REPO:$IMAGE_TAG
          docker push $ECR_REGISTRY/$UAT_ECR_REPO:latest

      - name: Output UAT image URI
        run: |
          ECR_REGISTRY=${{ steps.login-uat-ecr.outputs.registry }}
          echo "UAT_IMAGE=$ECR_REGISTRY/$UAT_ECR_REPO:$IMAGE_TAG" >> $GITHUB_ENV

  prod_deploy:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Prod ECR
        id: login-prod-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull latest UAT image
        run: |
          ECR_REGISTRY=${{ steps.login-prod-ecr.outputs.registry }}
          UAT_IMAGE=$(aws ecr describe-images \
          --repository-name $UAT_ECR_REPO \
          --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' \
          --output text)
          docker pull $ECR_REGISTRY/$UAT_ECR_REPO:$UAT_IMAGE

      - name: Tag and push to Prod
        run: |
          docker tag $ECR_REGISTRY/$UAT_ECR_REPO:$UAT_IMAGE $ECR_REGISTRY/$PROD_ECR_REPO:latest
          docker push $ECR_REGISTRY/$PROD_ECR_REPO:latest
