name: Consumer Service â€“ Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - feature 
    paths:
      - services/consumer-service/**
      - terraform/**
      - .github/workflows/consumer.yml
  pull_request:
    branches:
      - main        # Trigger on PRs targeting main
    paths:
      - services/consumer-service/**
      - terraform/**
      - .github/workflows/consumer.yml

env:
  AWS_REGION: us-east-1
  UAT_ECR_REPO: uat-health-monitor-consumer
  PROD_ECR_REPO: prod-health-monitor-consumer
  UAT_ECS_CLUSTER: uat-iot-health-monitor
  UAT_ECS_SERVICE: iot-consumer
  PROD_ECS_CLUSTER: prod-iot-health-monitor
  PROD_ECS_SERVICE: iot-consumer

jobs:
  uat_deploy:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to UAT ECR
        id: login-uat-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image for UAT
        working-directory: services/consumer-service
        run: |
          ECR_REGISTRY=${{ steps.login-uat-ecr.outputs.registry }}
          IMAGE_SHA=uat-${GITHUB_SHA}      # Immutable image tag
          IMAGE_LATEST=uat-latest          # Optional convenience tag

           # Build image with both SHA and latest tag
          docker build -t $ECR_REGISTRY/$UAT_ECR_REPO:$IMAGE_SHA -t $ECR_REGISTRY/$UAT_ECR_REPO:$IMAGE_LATEST .
          
           # Push both tags
          docker push $ECR_REGISTRY/$UAT_ECR_REPO:$IMAGE_SHA
          docker push $ECR_REGISTRY/$UAT_ECR_REPO:$IMAGE_LATEST

          # Export for Terraform
          echo "UAT_IMAGE_SHA=$ECR_REGISTRY/$UAT_ECR_REPO:$IMAGE_SHA" >> $GITHUB_ENV
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.3
      - name: Terraform Init & Apply for UAT
        working-directory: terraform
        run: |
          terraform workspace select -or-create "$TERRAFORM_WORKSPACE_UAT"
          terraform init
          terraform apply -auto-approve -var="consumer_image_tag=${{ env.UAT_IMAGE_SHA }}"

  prod_deploy:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to PROD ECR
        id: login-prod-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull UAT image and push to PROD
        run: |
          IMAGE_SHA=prod-${GITHUB_SHA::8}
          IMAGE_LATEST=prod-latest

          # Pull UAT SHA image
          docker pull ${{ steps.login-prod-ecr.outputs.registry }}/${UAT_ECR_REPO}:uat-${GITHUB_SHA::8}

          # Tag it for PROD
          docker tag ${{ steps.login-prod-ecr.outputs.registry }}/${UAT_ECR_REPO}:uat-${GITHUB_SHA::8} \
                     ${{ steps.login-prod-ecr.outputs.registry }}/${PROD_ECR_REPO}:$IMAGE_SHA
          docker tag ${{ steps.login-prod-ecr.outputs.registry }}/${UAT_ECR_REPO}:uat-${GITHUB_SHA::8} \
                     ${{ steps.login-prod-ecr.outputs.registry }}/${PROD_ECR_REPO}:$IMAGE_LATEST

          # Push to PROD
          docker push ${{ steps.login-prod-ecr.outputs.registry }}/${PROD_ECR_REPO}:$IMAGE_SHA
          docker push ${{ steps.login-prod-ecr.outputs.registry }}/${PROD_ECR_REPO}:$IMAGE_LATEST

          echo "PROD_IMAGE_SHA=$IMAGE_SHA" >> $GITHUB_ENV
          echo "PROD_IMAGE_LATEST=$IMAGE_LATEST" >> $GITHUB_ENV

      - name: Force ECS service to deploy latest PROD image
        run: |
          aws ecs update-service \
            --cluster ${{ env.PROD_ECS_CLUSTER }} \
            --service ${{ env.PROD_ECS_SERVICE }} \
            --force-new-deployment


